[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-main = { version = "0.5.0", features = ["bench"] }
itertools = "0.14.0"
regex = "1.12.2"
good_lp = { version = "1.14.2", features = ["highs"], default-features = false }